# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_path_local": "10-process-data.ipynb",
         "get_path_zip": "10-process-data.ipynb",
         "make_segment": "10-process-data.ipynb",
         "get_left_up": "10-process-data.ipynb",
         "get_white_precent": "10-process-data.ipynb",
         "set_labels_dict": "10-process-data.ipynb",
         "label_func": "10-process-data.ipynb",
         "imagesAndLabels": "10-process-data.ipynb",
         "imagesAndLabelsDict": "10-process-data.ipynb",
         "slice_image": "10-process-data.ipynb",
         "segment_images": "10-process-data.ipynb",
         "std_length": "10-process-data.ipynb",
         "std_width": "10-process-data.ipynb",
         "overlap": "10-process-data.ipynb",
         "get_overlap": "10-process-data.ipynb",
         "get_segmented_image_files": "10-process-data.ipynb",
         "sort_segmented_image_files": "10-process-data.ipynb",
         "get_training_files": "10-process-data.ipynb",
         "get_holdout_files": "10-process-data.ipynb",
         "training_set": "10-process-data.ipynb",
         "holdout_set": "10-process-data.ipynb",
         "global_path_to_data": "10-process-data.ipynb",
         "already_set_labels": "10-process-data.ipynb",
         "already_segmented": "10-process-data.ipynb",
         "already_sorted": "10-process-data.ipynb",
         "get_dls": "10-process-data.ipynb"}

modules = ["dataloader.py"]

doc_url = "https://Vanderbilt-PTY-Data-Science.github.io/digital_connoisseur/"

git_url = "https://github.com/Vanderbilt-PTY-Data-Science/digital_connoisseur/tree/main/"

def custom_doc_links(name): return None
